### ISSUE TITLE
Activation error

### ISSUE THREAD

**Issue by blackburnravers** [Andrew-Jenkins/wp_plugin_hearthis#12]
When i try to activate the plugin from my wordpress admin page I get this error:-

Plugin could not be activated because it triggered a fatal error.

Fatal error: Class 'Phar' not found in /***_/**_*/wp-content/plugins/hearthisat/httpful.phar on line 3

**Comment by RevolteSolutions** [comment]
okay ...it could be a problem of your hoster's php installation. maybe you are not allowd to use php packed phar archives. can you tell if this file http full.phar really exists on you plugin root and what version of php you use

**Comment by blackburnravers** [comment]
Alright pal, I'm running WordPress 4.3.1, my php is php5.6, but I just
spoke to my host and they don't allow php packed phar archives which is
pretty gutting, is there any work around that could work?

**Comment by blackburnravers** [comment]
Nice one Andrew, I'll keep an eye out for the update, thanks for sorting
this out.

**Comment by blackburnravers** [comment]
Hello there,

I just signed the petition "Walkers Crisps Bring back Ready Salted
Chipsticks" and wanted to see if you could help by adding your name.

Our goal is to reach 5,000 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/y5Hh7qyLQt

Thanks!
Rhys
